// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFromLeader() {
  return window['go']['main']['App']['ReadFromLeader']();
}

export function WriteToLeader(arg1) {
  return window['go']['main']['App']['WriteToLeader'](arg1);
}
