// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFromLeader():Promise<string>;

export function WriteToLeader(arg1:string):Promise<void>;
